### ISSUE TITLE
MA 7.1 sample only decodes 6 channels

### ISSUE THREAD

**Issue by Nevcairiel** [foo86/dcadec#1]
The following sample only decodes 6 channels, while a reference decoder properly decodes all 8:
http://samples.libav.org/A-codecs/DTS/dts/Master%20Audio%207.1%2024bit.dts

dcadec output:
DTS Core Audio: 5.1 ch, 48000 Hz, 24 bit, 1536 kbps
DTS-HD Master Audio: 8 ch, 48000 Hz, 24 bit

The resulting .wav file only has 6 channels, however.

**Comment by foo86** [comment]
This particular sample doesn't have downmix coefficients embedded into the stream (this is the only such 7.1 channel sample I have seen so far). Right now I don't know if that means that some default (unknown) coefficients are used, or that the downmix has not been performed and that all channels should be simply output as is. Will try to verify this with reference decoder.

**Comment by foo86** [comment]
I couldn't comprehend what the reference decoder is doing with this file. This sample consists of two XLL channel sets with (C + L + R + Ls + Rs + LFE1) speakers in channel set 0 and (Lw + Rw) speakers in channel set 1 (speaker names are native DTS names as per ETSI TS 102 114). This corresponds to 7.1(wide) channel layout. Yet the WAV file produced by reference decoder has channel mask 0x63f which is 7.1 channel layout. Channels from channel set 0 are left untouched yet rearranged (normal surround channels become rear surround). Front wide channels from channel set 1 are post-processed somehow to become surround channels (WTF?). I suspect what the reference decoder is doing is not a lossless operation.

The best I can do in this situation is to output all channels as-is and produce 7.1(wide) channel layout.

**Comment by Nevcairiel** [comment]
Thanks, it decodes fine now. As you said, the order of the channels is different, but which one is correct I couldn't say. Maybe I should try encoding a few different 7.1 layouts and see if one of them behaves the same way.
