### ISSUE TITLE
x64 build

### ISSUE THREAD

**Issue by Aleksoid1978** [foo86/dcadec#14]
As i see - there is no way to build x64 version.

**Comment by Nevcairiel** [comment]
Of course there is, just need to specify the compiler to be used in the command line.
Since you want Windows, here for mingw:

make CONFIG_WINDOWS=1 CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar

**Comment by Aleksoid1978** [comment]
I use msys_ming from here - http://xhmikosr.1f0.de/tools/msys/MSYS_MinGW-w64_GCC_492_x86-x64.7z
and you command line isn't working, lot of error:

$ make CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar
x86_64-w64-mingw32-gcc  -o dcadec dcadec.o libdcadec/libdcadec.a -lm
d:/sdk/mmsys86/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `dcadec.o' is incompatible with i386:x86-64 output
d:/sdk/mmsys86/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file`libdcadec/libdcadec.a(dca_waveout.o)' is incompatible with i386:x86-64 output
d:/sdk/mmsys86/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/bin/ld.exe: i386 architecture of input file `libdcadec/libdcadec.a(ta.o)' is incompatible with i386:x86-64 output
dcadec.o: In function`main':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:140: undefined reference to `___main'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:146: undefined reference to`_getopt'
dcadec.o: In function `print_help':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:39: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:39: undefined reference to `_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:39: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:39: undefined reference to `_fprintf'
dcadec.o: In function`main':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:180: undefined reference to `_optind'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:186: undefined reference to`_strcmp'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:186: undefined reference to `_dcadec_stream_open'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:196: undefined reference to`_dcadec_stream_read'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:208: undefined reference to `_dcadec_context_create'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:215: undefined reference to`_dcadec_context_parse'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:225: undefined reference to `_optind'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:232: undefined reference to`_strcmp'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:243: undefined reference to `__imp__SetConsoleCtrlHandler@8'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:250: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:250: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:287: undefined reference to`_dcadec_context_parse'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:257: undefined reference to `_dcadec_context_filter'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:271: undefined reference to`_dcadec_stream_read'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:277: undefined reference to `_dcadec_stream_progress'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:279: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:279: undefined reference to `_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:203: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:210: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:211: undefined reference to`_dcadec_stream_close'
dcadec.o: In function `print_info':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:84: undefined reference to`_dcadec_context_get_exss_info'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:95: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:95: undefined reference to`_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:98: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:98: undefined reference to`_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:101: undefined reference to `_dcadec_context_free_exss_info'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:104: undefined reference to`_dcadec_context_get_core_info'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:107: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:107: undefined reference to`_fputc'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:108: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:108: undefined reference to`_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:114: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:114: undefined reference to`_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:116: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:116: undefined reference to`_fputc'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:117: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:117: undefined reference to`_fputc'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:118: undefined reference to `_dcadec_context_free_core_info'
dcadec.o: In function`main':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:188: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:188: undefined reference to`_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:295: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:295: undefined reference to`_fputc'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:303: undefined reference to `_dcadec_context_destroy'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:304: undefined reference to`_dcadec_stream_close'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:226: undefined reference to `_dcadec_context_destroy'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:227: undefined reference to`_dcadec_stream_close'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:197: undefined reference to `_dcadec_strerror'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:197: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:197: undefined reference to `_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:198: undefined reference to`_dcadec_stream_close'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:252: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:252: undefined reference to`_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:260: undefined reference to `_dcadec_strerror'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:288: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:288: undefined reference to `_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:210: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:267: undefined reference to `_dcadec_strerror'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:272: undefined reference to`_dcadec_strerror'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:288: undefined reference to `_dcadec_strerror'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:297: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:297: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:216: undefined reference to`_dcadec_strerror'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:216: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:216: undefined reference to`_fprintf'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:235: undefined reference to `_dcadec_context_destroy'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:236: undefined reference to`_dcadec_stream_close'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:234: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:234: undefined reference to`_fwrite'
dcadec.o: In function `print_info':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:112: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:112: undefined reference to `_fwrite'
dcadec.o: In function`main':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:299: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:299: undefined reference to`_fwrite'
dcadec.o: In function `print_info':
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:87: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:87: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:89: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:89: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:104: undefined reference to`_dcadec_context_get_core_info'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:91: undefined reference to `__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:91: undefined reference to`_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:97: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:93: undefined reference to`__imp___iob'
d:\Distrib\Development\C++\Source\dcadec/dcadec.c:93: undefined reference to `_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function`write_header':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:72: undefined reference to `___popcountsi2'
libdcadec/libdcadec.a(dca_waveout.o): In function`write_raw':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:45: undefined reference to `_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function`write_int':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:65: undefined reference to `_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function`write_raw':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:45: undefined reference to `_fwrite'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:45: undefined reference to`_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function `write_int':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:65: undefined reference to`_fwrite'
libdcadec/libdcadec.a(dca_waveout.o):d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:54: more undefined references to `_fwrite' follow
libdcadec/libdcadec.a(dca_waveout.o): In function`write_header':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:122: undefined reference to `_ferror'
libdcadec/libdcadec.a(dca_waveout.o): In function`dcadec_waveout_write':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:205: undefined reference to `_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function`dcadec_waveout_open':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:218: undefined reference to `_fopen'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:223: undefined reference to`__imp___dup'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:225: undefined reference to `__imp___setmode'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:230: undefined reference to`__imp___close'
libdcadec/libdcadec.a(dca_waveout.o): In function `dcadec_waveout_close':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:256: undefined reference to`_fseeko64'
libdcadec/libdcadec.a(dca_waveout.o): In function `write_int':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:65: undefined reference to`_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function `dcadec_waveout_close':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:262: undefined reference to`_fseeko64'
libdcadec/libdcadec.a(dca_waveout.o): In function `write_int':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:65: undefined reference to`_fwrite'
libdcadec/libdcadec.a(dca_waveout.o): In function `dcadec_waveout_close':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/dca_waveout.c:270: undefined reference to`_fclose'
libdcadec/libdcadec.a(ta.o): In function `get_or_alloc_ext_header':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:68: undefined reference to`_malloc'
libdcadec/libdcadec.a(ta.o): In function `ta_free':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:243: undefined reference to`_free'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:244: undefined reference to `_free'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:243: undefined reference to`_free'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:244: undefined reference to `_free'
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:243: undefined reference to`_free'
libdcadec/libdcadec.a(ta.o):d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:244: more undefined references to `_free' follow
libdcadec/libdcadec.a(ta.o): In function`ta_alloc_size':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:128: undefined reference to `_malloc'
libdcadec/libdcadec.a(ta.o): In function`get_or_alloc_ext_header':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:68: undefined reference to `_malloc'
libdcadec/libdcadec.a(ta.o): In function`ta_zalloc_size':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:147: undefined reference to `_calloc'
libdcadec/libdcadec.a(ta.o): In function`get_or_alloc_ext_header':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:68: undefined reference to `_malloc'
libdcadec/libdcadec.a(ta.o): In function`ta_realloc_size':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:185: undefined reference to `_realloc'
libdcadec/libdcadec.a(ta.o): In function`get_or_alloc_ext_header':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:68: undefined reference to `_malloc'
libdcadec/libdcadec.a(ta.o): In function`ta_free':
d:\Distrib\Development\C++\Source\dcadec/libdcadec/ta.c:244: undefined reference to `_free'
d:/sdk/mmsys86/mingw/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/../../../../x86_64-w64-mingw32/lib/../lib/libmingw32.a(lib64_libmingw32_a-crt0_c.o):(.text.startup+0x25): undefined reference to`WinMain'
collect2.exe: error: ld returned 1 exit status
make: **\* [dcadec] Error 1

**Comment by Aleksoid1978** [comment]
But - it's work without CONFIG_WINDOWS=1. Thanks.

**Comment by Nevcairiel** [comment]
Need to do "make clean" first before switching from 32 to 64-bit.
