### ISSUE TITLE
dcacut isn't compiled?

### ISSUE THREAD

**Issue by MarcusJohnson91** [foo86/dcadec#26]
When I CD to the directory, and run make, or make -ofast dcadec is compiled just fine, but dcacut isn't anymore.

**Comment by Nevcairiel** [comment]
This seems to be intentional judging from the Makefile. You can run "make all" to build dcacut as well.

**Comment by kasper93** [comment]
Or `make dcacut` to build dcacut only.
5 kwi 2015 15:09 "Hendrik Leppkes" notifications@github.com napisał(a):

**Comment by MarcusJohnson91** [comment]
Of course, that's the only command I didn't think to run. I just thought it was weird how when I ran make dcacut it was only 18kb, and didn't seem to do much, and the filesize seemed suspect.

**Comment by bumblebritches57** [comment]
You can close this btw, I was wrong, and this post is useless at best, and misleading at worst.
