### ISSUE TITLE
Sync error when decoding DTS HD MA

### ISSUE THREAD

**Issue by r0lZ** [foo86/dcadec#38]
I use dcadec (with eac3to) to convert DTS HD MA tracks from 3D BDs to other formats.  I have already encountered several times a problem when decoding some tracks.  The dcadec reports a "Synchronisation error".  However, I don't think it's really an error in the track, because the track has been extracted from a good commercial BD, eac3to can extract the DTS core without problem, the other DTS decoders I've tested (Libav and ArcSoft) have no problem, all players can play the DTS (core or HDMA) without problem, I can't hear any audible glitch and I've encountered the same problem already 3 times, with totally different commercial BDs.  So, I suppose that the problem is caused by a little bug in dcadec (but of course I can't be sure).

Here is a sample: http://download.videohelp.com/r0lZ/tmp/DTS_HD_MAsync_bug_sample.dts

**Comment by Nevcairiel** [comment]
FWIW, the libdcadec wrapper in FFmpeg does not encounter any error - which indicates that the dcadec decoder is working fine, and the problem may be in reading/parsing the file.

**Comment by madshi** [comment]
Decoding runs through in eac3to, too, when not using the "DCADEC_FLAG_STRICT" flag. It's that flag which results in the decoding failure. So this looks like either a bug in DcaDec to me, or a damaged audio file. I doubt the eac3to parser is at fault here...

**Comment by Nevcairiel** [comment]
If its an error that only shows up in strict mode, then the file may be slightly "bad", but not bad enough to be considered a fatal error, which is probably why other decoders process it just fine. dcadec in strict mode is far stricter than other dca decoders I've tried out.

**Comment by madshi** [comment]
That's quite possible. But I think it would still make sense to double check, just to be safe.
