### ISSUE TITLE
proper handling of clipping

### ISSUE THREAD

**Issue by madshi** [foo86/dcadec#40]
dcadec reports "Clipping detected in XLL output" with the following sample:

http://madshi.net/clipping.dtshd

So I've checked the upper byte in the 32bit samples returned by dcadec, but it's empty. How do you handle clipping? Do you really hard clip it? Wouldn't it make more sense to actually store it into the 32bit sample buffer? I mean the buffer is already 32bit, anyway, so why not make use of that? Then eac3to could detect the clipping and run a 2nd pass to lower overall volume. Maybe it would make sense to add a new flag/option to allow this behaviour?

**Comment by Nevcairiel** [comment]
Set the DCADEC_FLAG_DONT_CLIP flag.

Majority of callers would expect the audio to be clipped into the valid range of the bitdepth dcadec specifies, so the default behavior seems fine, and the flag could accommodate your use-case.

**Comment by madshi** [comment]
Hmmmmm... Good catch!

However, doing so changes the final output and removes the warnings, but still the 32bit output buffer has an empty upper byte. That doesn't make a lot of sense to me. Am I missing something?

**Comment by Nevcairiel** [comment]
Seems to be working here.
http://i.imgur.com/Ed1VVSx.png

Top is with clipping and handled as 24-bit, bottom is without clipping and handled as higher bitdepth. The waveform is not clipped and looks "natural"

**Comment by madshi** [comment]
What can I say? I activated "DCADEC_FLAG_DONT_CLIP" and then checked the top byte in each 32bit sample returned by dcadec. It was always either 00 or FF, never anything else. So what does dcadec do exactly if there's a sample which has data which doesn't fit into 24bit? The only two "lossless" options I see is either clipping, or allowing the data to spill into the upper 8bit of the 32bit sample storage.

**Comment by Nevcairiel** [comment]
Actually the overflow is so small that it doesn't spill into the top 8 bits, but only into bit 24, which still goes above the range of 24-bit signed integers, since thats were the sign bit would go.

This check should reveal them:

> if ((samples[ch][n] & 0xFF800000) != 0x00000000 && (samples[ch][n] & 0xFF800000) != 0xFF800000)
>     Log("Overflow!");

**Comment by madshi** [comment]
Ah, makes sense, thanks.
