### ISSUE TITLE
FIR filter for DTS Core?

### ISSUE THREAD

**Issue by MarcusJohnson91** [foo86/dcadec#42]
Does this affect the lossless-ness of the output file (for streams with the XLL extension I mean)? does it degrade sound quality? It'd be nice if the help page went into more detail on what exactly this is.

**Comment by foo86** [comment]
`-f` flag only affects LFE channel in bit-inexact (floating point) mode. It forces the FIR filter from the spec to be used for LFE channel interpolation. By default, libdcadec uses unspecified IIR filter for LFE channel interpolation that reference decoder seems to be actually using. I don't know which is higher quality. IIR filter produces slightly louder result than FIR.

**Comment by MarcusJohnson91** [comment]
Thanks
