### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by madshi** [foo86/dcadec#5]
Your readme says GPL. However, your download contains both the GPL and LGPL license texts. Is your decoder available as LGPL, too? I'd really like to use it for eac3to, but probably can't do that if it's only available as GPL, correct?

If LGPL is available, I have one more question: Are you planning to create some sort of win32 "libDcaDec.dll"? If you do I'd wait for that. Otherwise I would create one myself.

Thanks!

**Comment by ghost** [comment]
In general, it'd be nice if the project would build as library out of the box. Then the FFmpeg patch could probably be merged too. (The patch is sitting on ffmpeg-devel's ML; @Nevcairiel  wrote it.)

**Comment by jamrial** [comment]
AFAIK it was relicensed as LGPL after it was requested on a previous github issue. The readme and the gpl license file were probably forgotten and skipped in the relicensing patch.
But yes, Makefile needs changes to build shared libraries (.dll, .so).

wm4: I'd say not until dcadec project introduces version defines for ABI concerns, and preferably can also build shared libraries.

**Comment by foo86** [comment]
> Your readme says GPL. However, your download contains both the GPL and LGPL license texts. Is your decoder available as LGPL, too?

The decoder library (i.e., all source files inside libdcadec/ subdirectory) is LGPL. The two demo applications (dcadec.c and dcacut.c) in top level directory are GPL (one can't apply LGPL to non-libraries I presume). Alternatively, one can relicense the whole source archive as GPL (I think LGPL implicitly allows this conversion).

> If LGPL is available, I have one more question: Are you planning to create some sort of win32 "libDcaDec.dll"?

With the latest changes the Win32 DLL should be buildable using MinGW-w64. I've only tried to do this on a Linux system. A command line similar to this should produce want you want probably:

```
CC=i686-w64-mingw32-gcc make CONFIG_WINDOWS=1 CONFIG_SHARED=1 CONFIG_SMALL=1 CONFIG_NDEBUG=1 libdcadec/libdcadec.dll
i686-w64-mingw32-strip libdcadec/libdcadec.dll
```

> The readme and the gpl license file were probably forgotten and skipped in the relicensing patch.

These are left on purpose, demo apps are GPL (README shows the help screen of dcadec binary which is GPL).

> In general, it'd be nice if the project would build as library out of the box.

I've committed some changes to address this.

**Comment by ghost** [comment]
> one can't apply LGPL to non-libraries I presume

This is wrong. LGPL is fine for standalone libs.

**Comment by madshi** [comment]
Looking good so far, at least there seems to be a valid win32 DLL file with reasonable exports.

Thank you!  :-)

**Comment by foo86** [comment]
> This is wrong. LGPL is fine for standalone libs.

So when you call an application a "standalone library" you can license it under LGPL? Sounds reasonable, will remove remaining references to GPL then.
