### ISSUE TITLE
Improve build system and introduce version defines

### ISSUE THREAD

**Issue by jamrial** [foo86/dcadec#6]
Making a single ticket since it's all more or less related.

Makefile currently builds a static library and two cli applications, but it still needs to build a shared library (See comments on issue #5) and an "install" target.
Additionally, the to-be-installed public header dca_context.h needs version defines (for library versioning) before it can be properly used by other projects.

Offtopic: Excellent work so far :)

**Comment by foo86** [comment]
Addressed some of these issues. Version defines will be added separately.

**Comment by simonbcn** [comment]
`make clean` does nothing.
